# Generated by Django 5.2.5 on 2026-01-26 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price per unit in KSH at time of order', max_digits=10, null=True),
        ),
    ]
