# Generated by Django 5.2.7 on 2026-01-27 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_ordering_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('saved', 'Saved'), ('paid', 'Paid'), ('shipped', 'Shipped'), ('complete_waiting_transport', 'Complete Waiting for Transport'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='saved', max_length=30),
        ),
    ]
