# Generated by Django 5.2.7 on 2026-02-02 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_order_order_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='mpesa_checkout_request_id',
            field=models.CharField(blank=True, help_text='M-Pesa checkout request ID', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='mpesa_phone_number',
            field=models.CharField(blank=True, help_text="Customer's M-Pesa phone number", max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='mpesa_transaction_id',
            field=models.CharField(blank=True, help_text='M-Pesa transaction ID', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_completed_at',
            field=models.DateTimeField(blank=True, help_text='When payment was completed', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_initiated_at',
            field=models.DateTimeField(blank=True, help_text='When payment was initiated', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', help_text='M-Pesa payment status', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('saved', 'Saved'), ('pending_payment', 'Pending Payment'), ('paid', 'Paid'), ('shipped', 'Shipped'), ('complete_waiting_transport', 'Complete Waiting for Transport'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='saved', max_length=30),
        ),
    ]
