# Generated by Django 5.2.7 on 2026-02-08 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_alter_order_product'),
        ('orders', '0013_cart'),
    ]

    operations = [
    ]
