# Generated by Django 5.2.7 on 2026-02-18 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_merge_0012_alter_order_product_0013_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='offer',
            field=models.CharField(blank=True, choices=[('', 'No Offer'), ('free_delivery', 'Free Delivery'), ('10_percent_discount', '10% Discount')], help_text='Special offer applied to this order', max_length=50, null=True),
        ),
    ]
