# Generated by Django 5.2.7 on 2025-11-17 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('customer', 'Customer'), ('supplier', 'Supplier'), ('consultant', 'Consultant')], default='customer', max_length=20),
        ),
    ]
