# Generated by Django 5.2.5 on 2026-01-26 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0004_consultantapplication_approved_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultantapplication',
            name='consultation_rate',
            field=models.DecimalField(decimal_places=2, default=5000, help_text='Consultation rate in KSH per hour/session', max_digits=10),
        ),
    ]
