# Generated by Django 5.2.5 on 2026-01-26 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0005_consultantapplication_consultation_rate'),
        ('suppliers', '0007_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='consultant_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='consultation',
            name='consultant_phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='consultation',
            name='consultation_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='consultation',
            name='specialization',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consultation_requests', to='suppliers.supplier'),
        ),
    ]
