# Generated by Django 5.2.7 on 2026-01-29 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0006_consultation_consultant_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='consultant_receipt_downloaded_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when consultant downloaded the receipt', null=True),
        ),
    ]
