# Generated by Django 5.2.7 on 2026-02-13 12:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0008_alter_consultantapplication_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='consultantapplication',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='consultantapplication',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultantapplication',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_consultant_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='consultantapplication',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for rejecting the application'),
        ),
    ]
