# Generated by Django 5.2.7 on 2026-02-19 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0009_consultantapplication_rejected_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='mpesa_checkout_request_id',
            field=models.CharField(blank=True, help_text='M-Pesa checkout request ID', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='mpesa_phone_number',
            field=models.CharField(blank=True, help_text="Customer's M-Pesa phone number", max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='mpesa_transaction_id',
            field=models.CharField(blank=True, help_text='M-Pesa transaction ID', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('pending_payment', 'Pending Payment'), ('scheduled', 'Scheduled'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='pending', max_length=20),
        ),
    ]
