# Generated by Django 5.2.7 on 2025-11-12 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_alter_product_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='consultation_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
