# Generated by Django 5.2.7 on 2025-11-18 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0003_supplier_consultation_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='offers',
            field=models.TextField(blank=True, help_text='Special offers like free delivery based on location'),
        ),
    ]
