# Generated by Django 5.2.7 on 2025-11-19 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0004_supplier_offers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='offers',
        ),
    ]
