# Generated by Django 5.2.7 on 2026-02-19 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0007_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='offer',
            field=models.CharField(blank=True, choices=[('', 'No Offer'), ('free_delivery', 'Free Delivery'), ('10_percent_discount', '10% Discount')], help_text='Special offer applied to this product', max_length=50, null=True),
        ),
    ]
