"""
Django settings for construction_hub project.

Generated by 'django-admin startproject' using Django 4.0.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'your-default-secret-key')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True') == 'True'

# M-Pesa Configuration
MPESA_CONFIG = {
    'CONSUMER_KEY': os.getenv('MPESA_CONSUMER_KEY', '1xceZ0S98zH1mTptv49gSMI0rM0UFjfwcVuA1yM27LA8qQME'),  # Provided consumer key
    'CONSUMER_SECRET': os.getenv('MPESA_CONSUMER_SECRET', '61oUGdIBt68vKW6mGFBqjTVDhg55zla6zORUotJXYF4RUjQ40TUsQRXUKhXFZ8mE'),  # Provided consumer secret
    'BUSINESS_SHORTCODE': os.getenv('MPESA_BUSINESS_SHORTCODE', '174379'),  # M-Pesa sandbox shortcode
    'PASSKEY': os.getenv('MPESA_PASSKEY', 'bfb279f9aa9bdbcf158e97dd71a467cd2e0c893059b10f78e6b72ada1ed2c919'),  # Sandbox passkey
    'ACCOUNT_REFERENCE': os.getenv('MPESA_ACCOUNT_REFERENCE', 'ConstructionHub'),
    'TRANSACTION_DESC': os.getenv('MPESA_TRANSACTION_DESC', 'Order Payment'),
    'CALLBACK_URL': 'https://latina-subtruncate-haughtily.ngrok-free.dev/mpesa/callback/',
    'BASE_URL': os.getenv('MPESA_BASE_URL', 'https://sandbox.safaricom.co.ke' if DEBUG else 'https://api.safaricom.co.ke'),  # Use sandbox for testing
}

# M-Pesa Consultation Callback URL
MPESA_CONSULTATION_CALLBACK_URL = os.getenv('MPESA_CONSULTATION_CALLBACK_URL', 'https://latina-subtruncate-haughtily.ngrok-free.dev/consultations/payment/callback/')

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', '127.0.0.1,localhost,testserver,latina-subtruncate-haughtily.ngrok-free.dev').split(',')

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.facebook',
    'django_extensions',
    'apps.accounts',
    'apps.suppliers',
    'apps.products',
    'apps.orders',
    'apps.consultations',
    'apps.dashboard',
    'apps.notifications',
    'apps.messaging',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'construction_hub.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'construction_hub.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Media files (user uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
STATICFILES_DIRS = [BASE_DIR / 'static']

# Media files (user uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Use the custom user model
AUTH_USER_MODEL = 'accounts.CustomUser'

# Allauth settings
SITE_ID = 1
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'
ACCOUNT_DEFAULT_HTTP_PROTOCOL = 'http'
ACCOUNT_EMAIL_VERIFICATION = 'none'
ACCOUNT_LOGIN_TEMPLATE = 'accounts/login.html'

SOCIALACCOUNT_ADAPTER = 'apps.accounts.adapters.CustomSocialAccountAdapter'

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': ['profile', 'email'],
        'AUTH_PARAMS': {'access_type': 'online'},
    },
    'facebook': {
        'METHOD': 'oauth2',
        'SCOPE': ['email', 'public_profile'],
        'AUTH_PARAMS': {'auth_type': 'reauthenticate'},
        'INIT_PARAMS': {'cookie': True},
        'FIELDS': [
            'id',
            'first_name',
            'last_name',
            'middle_name',
            'name',
            'name_format',
            'picture',
            'short_name'
        ],
        'EXCHANGE_TOKEN': True,
        'LOCALE_FUNC': 'path.to.callable',
        'VERIFIED_EMAIL': False,
        'VERSION': 'v7.0',
    },
}

# Email settings
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'victorjuniormunene@gmail.com'
EMAIL_HOST_PASSWORD = 'uasu jfjc smcv jrkr'
DEFAULT_FROM_EMAIL = 'victorjuniormunene@gmail.com'
ADMIN_EMAIL = 'victorjuniormunene@gmail.com'

# Africa's Talking SMS Configuration
AFRICASTALKING_USERNAME = os.getenv('AFRICASTALKING_USERNAME', 'victortech1')
AFRICASTALKING_API_KEY = os.getenv('AFRICASTALKING_API_KEY', 'db3c0fd20d07bbed')

# Beem Africa SMS Configuration
BEEM_AFRICA_API_KEY = os.getenv('BEEM_AFRICA_API_KEY', '0409d6573b96eafb')
BEEM_AFRICA_SECRET_KEY = os.getenv('BEEM_AFRICA_SECRET_KEY', 'YmZjMWZkYTFhNWQ5OTQ5MDMwMDAwOTU1Y2U5ODBkYjExMWRlYzQ2ODhlZmUxMmRjMmU5MWI3YTljZGU3NGM5Mw==')
BEEM_AFRICA_SENDER_ID = os.getenv('BEEM_AFRICA_SENDER_ID', None)
BEEM_AFRICA_BASE_URL = os.getenv('BEEM_AFRICA_BASE_URL', 'https://apisms.beem.africa')
