# Generated by Django 5.2.7 on 2025-11-20 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_price_product_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('cement', 'Cement & Concrete'), ('steel', 'Steel & Metals'), ('wood', 'Wood & Timber'), ('electrical', 'Electrical'), ('plumbing', 'Plumbing'), ('tools', 'Tools & Equipment'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
