# Generated by Django 5.2.7 on 2026-02-02 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_available_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quality',
            field=models.CharField(choices=[('standard', 'Standard'), ('premium', 'Premium'), ('high_end', 'High-End')], default='standard', help_text='Quality level of the product', max_length=50),
        ),
    ]
